### ISSUE TITLE
How to embed finplot in a custom pyqt5 window?

### ISSUE THREAD

**Issue by idm9612** [highfestiva/finplot#10]
The import module of the pinplot is pyqtgraph, so it is compatible, but I don't know how to upload it.

Please tell me how to upload the pinplot to the pyqt5 window.

Maybe I've been struggling with this for months.

**Comment by idm9612** [comment]
I solved it. It was really ridiculous.

**Comment by highfestiva** [comment]
Don't know what you're asking. Try `pip install finplot`. Once in a while I add feature and update the pipy directory. So try running `pip install -U finplot` every now and then to update your installation.

**Comment by xyberian-sg** [comment]
I think the question is, how to embed an instance of finplot into QMainWindow or QWidget?

**Comment by highfestiva** [comment]
I see. There is no support currently for this. But it sounds like a good idea. Renaming and reopening.

**Comment by highfestiva** [comment]
I'm sorry to say I found it to be impossible to do in a nice way due to pyqtgraph's internals (which I base finplot on). That said, I'm going to come up with something you can use, but it requires you to adapt to finplot unfortunately, instead of the other way around.

**Comment by xyberian-sg** [comment]
Thanks for your follow-up note.  While it might not be perfect, but it's going to be very helpful for those developing applications with finplot and other GUI features.

**Comment by highfestiva** [comment]
Hi again, my bad. After looking deeply into pyqtgraph I found a way to fairly simply fix a number of issues without sacrificing much. After [605a2468](https://github.com/highfestiva/finplot/commit/605a246825a4423975cb1dbecaebd4c2dd3285ca), you can do this:

````python
import finplot as fplt
from PyQt5.QtWidgets import QGraphicsView, QComboBox
from PyQt5.QtGui import QApplication, QGridLayout

app = QApplication([])
win = QGraphicsView()
layout = QGridLayout()
win.setLayout(layout)
win.resize(400, 300)

combo = QComboBox()
combo.addItem('Alpha')
combo.addItem('Beta')
combo.addItem('Gamma')
layout.addWidget(combo, 0, 0, 1, 1)

ax_a,ax_b = fplt.create_plot_widget(win, rows=2)
win.axs = [ax_a, ax_b] # finplot requres this property
layout.addWidget(ax_a.ax_widget, 1, 0, 1, 1)
layout.addWidget(ax_b.ax_widget, 1, 1, 1, 1)

# plot something
x = list(range(100))
y0 = [50-v/(v%3+1) for v in x]
y1 = [80-v/(v%9+5) for v in x]
fplt.plot(x, y0, color='#060', ax=ax_a)
fplt.plot(x, y1, color='#800', ax=ax_b)

fplt.show(qt_exec=False) # prepares plots when they're all setup
win.show()
app.exec_()
````

I'm going to add an example and pipify in a few days.

**Comment by highfestiva** [comment]
[Example](https://github.com/highfestiva/finplot/blob/master/finplot/example-embed.py) added. Please look at it and see if it fulfills your needs.

**Comment by xyberian-sg** [comment]
Yes, it does work for me.  Thanks a lot!

**Comment by Ioanni5** [comment]
Hello, 

when I try to run the example code I get the error

AttributeError: module 'finplot' has no attribute 'create_plot_widget'

my finplot version is 1.0.1

what am I missing?

**Comment by highfestiva** [comment]
This I've not yet pipified, so you need to fetch the source code from github in order to test it. If all goes well, I'll package it in a day or two. @idm9612 does this work for you too?

**Comment by highfestiva** [comment]
I've fine with what I've got for now. The embedding api is not perfect and has some bugs, but it will have to do. @Ioanni5 to fetch the new version go `pip install -U finplot` and v1.1 is yours (where you can `create_plot_widget()`).

**Comment by Protomolekule** [comment]
>I know that thread is old. But there must be some changes because I can't run this example. It crashes at 
`ax_a,ax_b = fplt.create_plot_widget(win, rows=2)`
I'm using python 3.10, pyqt 5.15, fplt '1.9.2-dev'
How can I create a propper QWidget to add into an existing layout? 
Thanks in advance

**Comment by highfestiva** [comment]
@Protomolekule Try examples/dockable.py. Works for me.

**Comment by Protomolekule** [comment]
Hi,
Thanks for the quick answer. Unfortunally same result.

It crashes in the file finplot.py at line 2139 without any further
message except 'Process finished with exit code -1073740791
(0xC0000409)'

The calls are:

Dockable.py:line16:


ax_a,ax_b = fplt.create_plot_widget(win, rows=2)

__init__.py:line 1470


       ax = prev_ax = _add_timestamp_plot(master=master,
prev_ax=prev_ax, viewbox=viewbox, index=n, yscale=ysc)


__init__.py:line 2154



   axes = {'bottom': _create_axis(pos='x', vb=viewbox,
orientation='bottom'),
            'right':  _create_axis(pos='y', vb=viewbox,
orientation='right')}



__init__.py:line 2139


        return EpochAxisItem(**kwargs)




__init__.py:line 107


class EpochAxisItem(pg.AxisItem):
    def __init__(self, vb, *args, **kwargs):
        super().__init__(*args, **kwargs)


I can't follow further 



Maybe its an issue with any other installed package. I dived into the
program and got more details. I' installed
Pyqtplot '0.13.3'
numpy '1.24.4'
Pandas '2.1.2'

Can you give me the versionnumbers used by your application?

Thanks in advance
Hans



 --- Original Nachricht ---
Betreff: Re: [highfestiva/finplot] How to embed finplot in a custom
pyqt5 window? (#10)
Von: "highfestiva" 
An: "highfestiva/finplot" 
CC: "Protomolekule" , "Mention" 
Datum: 24.11.2023 14:54












@Protomolekule [1] Try examples/dockable.py. Works for me.



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you were mentioned.Message ID: 





Links:
------
[1] https://github.com/Protomolekule
[2]
https://github.com/highfestiva/finplot/issues/10#issuecomment-1825709587
[3]

**Comment by highfestiva** [comment]
@Protomolekule What library versions are you using?

**Comment by Protomolekule** [comment]
Hi,

I found the source and solution for that issue. It seems that the
finplot 1.9.3 which I am using needs PyQt6. With PyQt5 I couldn't get
it running. Was not visible enough for my tired eyes...

Thanks for your support. I will the next weeks find time to go deeper
into finplot, because it seems to be the sophisticatest plot tool.
Great work, my coffee machine is heating up ;-)

Regards

Hans


--- Original Nachricht ---
Betreff: Re: [highfestiva/finplot] How to embed finplot in a custom
pyqt5 window? (#10)
Von: "highfestiva" 
An: "highfestiva/finplot" 
CC: "Protomolekule" , "Mention" 
Datum: 24.11.2023 21:51












@Protomolekule [1] What library versions are you using?



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you were mentioned.Message ID: 





Links:
------
[1] https://github.com/Protomolekule
[2]
https://github.com/highfestiva/finplot/issues/10#issuecomment-1826077375
[3]

**Comment by Protomolekule** [comment]
Sorry, once again

  File
"C:\DATEN\workshop\development\python\Trading_6\venv\lib\site-packages\finplot\__init__.py",
line 1929, in show
    if win.show_maximized:
AttributeError: 'DockArea' object has no attribute 'show_maximized'.
Did you mean: 'showMaximized'?

Is this a typo or do I call it wrong?


I've changed this to:

            if win.showMaximized or win.show_maximized:
                win.showMaximized()
            else:

                win.show()

Regards

Hans




--- Original Nachricht ---
Betreff: Re: [highfestiva/finplot] How to embed finplot in a custom
pyqt5 window? (#10)
Von: "highfestiva" 
An: "highfestiva/finplot" 
CC: "Protomolekule" , "Mention" 
Datum: 24.11.2023 21:51












@Protomolekule [1] What library versions are you using?



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you were mentioned.



 

Links:
------
[1] https://github.com/Protomolekule
[2]
https://github.com/highfestiva/finplot/issues/10#issuecomment-1826077375
[3]

**Comment by Protomolekule** [comment]
Hi,


yes I found that. Was just wondering about the error message. I will
go deeper in the usage next week. 


Thanks and Regards 
Hans


Am 27.11.2023 16:17 schrieb highfestiva :

Hi,


yes I found that. Was just wondering about the error message. I will
go deeper in the usage next week. 


Thanks and Regards 
Hans


Am 27.11.2023 16:17 schrieb highfestiva :







That is now on the line 2031. If you look at the line above, you see a
check for if it's either a FinWindow, or if you want Qt exec() called.
You probably want to run Qt exec() yourself, as you're composing your
own application, so pass qt_exec=False to show and you can handle the
maximization of your window yourself.



—
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].
You are receiving this because you were mentioned.Message ID: 



Links:
------
[1]
https://github.com/highfestiva/finplot/issues/10#issuecomment-1828035093
[2]

**Comment by Celestios** [comment]
Hi, with this code i get below error:
`class Plot(QGraphicsView):
    def __init__(self, df):
        super().__init__()
        self.layout = QVBoxLayout()
        self.setLayout(self.layout)
        self.ax = fp.create_plot_widget(self)
        self.axs = [self.ax]
        self.layout.addWidget(self.ax.ax_widget)
        fp.candlestick_ochl(df[['BO', 'BC', 'BH', 'BL']], ax=self.ax)
        fp.refresh()`

`line 16, in __init__
    self.layout.addWidget(self.ax.ax_widget)
TypeError: 'PySide6.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide6.QtWidgets.QBoxLayout.addWidget(PlotWidget)
Supported signatures:
  PySide6.QtWidgets.QBoxLayout.addWidget(PySide6.QtWidgets.QWidget, int = 0, PySide6.QtCore.Qt.AlignmentFlag = Default(Qt.Alignment))`
