### ISSUE TITLE
complicated.py example not smooth panning.

### ISSUE THREAD

**Issue by shujaatak** [highfestiva/finplot#203]
While panning the chart flicker after almost every 1second. There might be some update running in behind but this makes the software look like immature. 

**Expected response:**
The chart should be smooth whether the data behind updates or not.

**Comment by shujaatak** [comment]
While there is this issue, I enjoy using Finplot!

**Comment by shujaatak** [comment]
I found that it's actually the problem with auto-scaling of chart!

While panning the the chart tries to automatically scale the candlesticks which creates a flickering effect. 

**Proposed solution:**
It would be nice if the auto-scaling happens just after the mouse-release action not while dragging the chart! It would remove this  seemingly ugly flickering effect.

**Comment by shujaatak** [comment]
OR
It would be nice to continuously scale the candlesticks  so that the user know what's happens with the chart while he/she pan the chart. Right now the chart auto-scale after some interval or when the user stops panning the chart for a while even though he/she does not release the mouse button yet.

**Comment by highfestiva** [comment]
The auto-scaling happens when the data is updated. You are right, it is immature when it comes to real-time applications, but it is not intended as such either. It is intended as a backtesting tool. You are free to use it for whatever you like, but there is no built-in support for real-time smoothness — nor with there ever be. https://github.com/highfestiva/finplot/wiki#what-it-is-not
