### ISSUE TITLE
AttributeError: module 'finplot' has no attribute 'candlestick_ohlc'

### ISSUE THREAD

**Issue by mauphung** [highfestiva/finplot#257]
This example code was working but suddenly it's stopped working with message:
import finplot as fplt
import yfinance

df = yfinance.download('AAPL')
fplt.candlestick_ochl(df[['Open', 'Close', 'High', 'Low']])
fplt.show()

<module>
    fplt.candlestick_ohlc(df[['Open', 'Close', 'High', 'Low']])
AttributeError: module 'finplot' has no attribute 'candlestick_ochl'

Please check if there Is any change recently.

**Comment by mauphung** [comment]
I unzip finplot into finplot directory and run finplotex.py example as belows, it plot the chart correctly. 
But when I copy this file finplotex.py to the other folder and run it. I got a message:
fplt.candlestick_ohlc(df[['Open', 'Close', 'High', 'Low']]) AttributeError: module 'finplot' has no attribute 'candlestick_ochl'

import sys
import yfinance as yf
import finplot as fplt  # https://github.com/highfestiva/finplot 

df = yf.download('SPY',start='2018-01-01', end = '2020-04-29')
fplt.candlestick_ochl(df[['Open','Close','High','Low']])
fplt.plot(df.Close.rolling(50).mean())
fplt.plot(df.Close.rolling(200).mean())
fplt.show()

Can anybody can help me to figure out why?
Thanks

**Comment by highfestiva** [comment]
The reason is the function in `finplot` is called `candlestick_ochl`, not `candlestick_ohlc`. The reason is to keep the column order consistent with `volume_ocv`. I considered changing, but eventually decided [against it](https://github.com/highfestiva/finplot/issues/212). I no longer remember the reason why I don't create an _ohlc to either warn or re-arrange the columns and forward, but I know there was a fairly good one.
