### ISSUE TITLE
Zoom out beyond graph

### ISSUE THREAD

**Issue by gAdrev** [highfestiva/finplot#324]
Hey,

First, thanks for the lib.

Is it possible to zoom out beyond the graph (I mean whatever is being plotted, the full series) fitting the window? Like most regular pyqtgraph plots would allow you to.
Ideally I would like to arbitrarly zoom out, or in a trend move the graph so it doesn't end in a corner and therefore doesn't look too scary :)

I've tried fiddling with auto range/limits, `side_margin` and `right_margin_candles` but can't seem to make it work.

**Comment by highfestiva** [comment]
Hi, there is currently no support for zooming outside of the range of the rendered data. What is the purpose of viewing this whitespace?

**Comment by gAdrev** [comment]
I'm plotting a live graph, and usually in any kind of trend if I want to zoom in to get bars to be a certain size, the graph will end up in the upper/lower corner. Psychologically I find it harder to buy/sell into the high/low, it's just a matter of habit. I typically don't have the graph end up in a corner when trading.

Anyways, I suspected it was built in after looking around the code, but wanted to confirm. Thanks anyways!

**Comment by highfestiva** [comment]
What do you think of tradingview's way of zooming? (I.e. m-wheel zooming only affects x-axis, y-axis is modified using drag-n-drop on the axis, and reset using a button.)

**Comment by gAdrev** [comment]
TV's zooming is fine, I think I've got used to it in fact. You can also zoom in/out of the Y axis there with the m-wheel if you place the pointer over the Y axis.

**Comment by highfestiva** [comment]
M-wheel zooming on the y-axis without reset would be simple to implement. My only concern then is that people might spend additional time y-zooming to get comfortable instead of spending that time analyzing (once they are accustomed to auto-zoom).

Or more broadly: is finplot a tool to allow you to do everything your way, or should it force you into doing it in the most efficient way in the long run.

Most libraries want the former, but I'm leaning towards the latter. It's also a matter of what the library is for: since it's mainly for backtesting, human psycology plays less of a role and fewer features means less maintenance and fewer bugs.

Leave this open and I'll ponder it some more.

**Comment by highfestiva** [comment]
Btw. `finplot.y_pad` defaults to 0.03 (i.e. 3% screenspace). If you set this to a larger number (say 0.2), you'll get more whitespace.  This is the number the m-wheel zoom will alter, if any.

**Comment by highfestiva** [comment]
From I psychological standpoint, I decided to only use auto-zoom. My hopes is that when you've used finplot enough, you'll feel confided that it will always zoom out to show everything, without the need of additional margins to ensure "everything is visible." At least I do, and with only one datapoint I'm closing this. :)
