### ISSUE TITLE
order book display

### ISSUE THREAD

**Issue by Fantasticer** [highfestiva/finplot#5]
hi,
is it possible to show the order book  with the plot?

**Comment by highfestiva** [comment]
Hi Fantasticer,

Nope, the reason is that the only purpose I see fit for this tool is to 
do instrument analysis and backtesting. If you add support for it, and 
send me a pull request, I'd be happy to add it to the library though.

Kind regards,
Jonas

------ Originalmeddelande ------
Från: "Fantasticer" <notifications@github.com>
Till: "highfestiva/finplot" <finplot@noreply.github.com>
Kopia: "Subscribed" <subscribed@noreply.github.com>
Skickat: 2019-08-23 11:36:42
Ämne: [highfestiva/finplot] order book display (#5)

**Comment by highfestiva** [comment]
Hm... I'll do it anyway. Even though I don't think many people will use it for bot development or backtesting analysis, coding it would be cool... :-/

**Comment by highfestiva** [comment]
I added support for orderbook via the horizontal volume functionality, https://github.com/highfestiva/finplot/commit/65dee9e0600cc07e7f477f798756bb9748833aba#diff-0d5d8ead8e5f7a5bb9555b59d33a4db3.
